### ISSUE TITLE
Triggering  tests through Jenkins on a self-hosted Selenium Server leads to Exceptions

### ISSUE THREAD

**Issue by rmadakasira** [ryojiosawa/cinnamon#11]
Hi,

I am able to run tests successfully through UI by clicking on "Execute Tests" in "Test Console" page. I am now trying to trigger tests through my Jenkins job, and it triggers the below error.  I am able to trigger tests when the "WebDriver Service Provide" is sauceLabs. 

Based on this I would imagine, I will have to make few more configuration changes, and I don't want to re-invent the wheel. Your help is appreciated. Thanks.

Mar 03, 2015 11:15:36 AM cinnamon.Ccli main
SEVERE: An unexpected error occurred. aborting test
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to java.util.Map
    at cinnamon.CinnamontTestSuite.getMapFromJson(CinnamontTestSuite.java:82)
    at cinnamon.CinnamontTestSuite.run(CinnamontTestSuite.java:158)
    at cinnamon.Ccli.run(Ccli.java:80)
    at cinnamon.Ccli.main(Ccli.java:48)

**Comment by yudiatsfdc** [comment]
this thread has moved to https://github.com/forcedotcom/cinnamon/issues/41
