### ISSUE TITLE
While i am in Developer Org , i get warning "Cinnamon can only run against a Sandbox or Developer Edition org"

### ISSUE THREAD

**Issue by sanjekum** [ryojiosawa/cinnamon#12]
I am into Develper org with   Cinnamon Apps installed into it. 
the URL is :https://cinnamon.na10.visual.force.com/apex/CN_Settings?sfdc.tabName=01rF0000000MZyY

It get the error as shown below. I have attched the screen shot as well.

WARNING 
![clipboard01](https://cloud.githubusercontent.com/assets/11309442/6479909/f824b6fc-c272-11e4-910c-cceb23d47716.jpg)

Warning:
Cinnamon can only run against a Sandbox or Developer Edition org
![clipboard01](https://cloud.githubusercontent.com/assets/11309442/6479908/e4a87b9a-c272-11e4-8d87-3999dc8d5dce.jpg)

**Comment by yudiatsfdc** [comment]
From your screen shot it doesn't look like this is a Developer Edition org. Sign up for a Developer Edition in developer.force.com/signup
