### ISSUE TITLE
Test Class not found in test console

### ISSUE THREAD

**Issue by sanjekum** [ryojiosawa/cinnamon#13]
I followed the example as provided in the blog https://github.com/forcedotcom/cinnamon/blob/master/README.md

I created PageObject Class , Vf page and Test Class as provided in the sample example. 
At present in into Salesforce Developer Org. 

When i Navigate to to the  Test Console tab. 
I do not see the Test Class which i can Click to execute. 
I have attached the screen as well. 
![test class not found in test console](https://cloud.githubusercontent.com/assets/11309442/6480038/11f57eac-c275-11e4-918a-60005bb903ad.jpg)

**Comment by yudiatsfdc** [comment]
Cinnamon only runs on Developer Edition and Sandbox. What edition is the org you installed cinnamon?
