### ISSUE TITLE
My domain issue

### ISSUE THREAD

**Issue by anuritab** [ryojiosawa/cinnamon#2]
Attempting to install cinamon to my domain. My domain is enabled in the org. 

This is the error when running the test.

Warning:
Cinnamon can only run against a Sandbox or Developer Edition org

**Comment by ryojiosawa** [comment]
@anuritab - could you send me your custom domain URL?

**Comment by anuritab** [comment]
https://rh--cint02.cs18.my.salesforce.com

**Comment by ryojiosawa** [comment]
Thank you.

**Comment by ryojiosawa** [comment]
This issue has been addressed.  The fix will be included in the next package version.

**Comment by ryojiosawa** [comment]
@anuritab - FYI.  This issue has been fixed.  The fix will be included in the next package release this Wednesday.  We will provide a link to install this new version tomorrow.  Please try it out and let me know if it fixes the problem you're seeing.

**Comment by ryojiosawa** [comment]
The fix is now available in Beta51 version:
https://login.salesforce.com/packaging/installPackage.apexp?p0=04td0000000N1MX
