### ISSUE TITLE
Tests not available

### ISSUE THREAD

**Issue by aaklaus** [ryojiosawa/cinnamon#7]
We updated our sandbox to the new version of Cinnamon.  After the upgrade, none of the old tests are available in the Test Console. I tried manually adding under Tests but that did not work either. The test classes are saved to the sandbox.
![screen shot 2014-05-05 at 1 24 49 pm](https://cloud.githubusercontent.com/assets/7341290/2882861/93880e06-d493-11e3-86ca-837115cbed4a.png)

**Comment by ryojiosawa** [comment]
@aaklaus - what value do you have in "Test Class Name Prefix" field in Settings page?  The default value is "Test" and Cinnamon looks for all Cinnamon classes whose name starts with "Test" or whatever value is provided in this setting field.

**Comment by aaklaus** [comment]
That fixed it — I had to change to our prefix.  Will remember for the next refresh.  Thanks for the quick response!

On May 5, 2014, at 1:31 PM, Ryo Osawa notifications@github.com wrote:

@aaklaus - what value do you have in "Test Class Name Prefix" field in Settings page? The default value is "Test" and Cinnamon looks for all Cinnamon classes whose name starts with "Test".

**Comment by ryojiosawa** [comment]
Great!  Glad to hear that trick fixed your issue :)
